### ISSUE TITLE
Repeating Groups with Multi-select data 

### ISSUE THREAD

**Issue by JacquelineMorrissette** [enketo/enketo-core#1000]
**Describe the bug**
When have a repeating group of questions based on a multi-select question, if an option is selected and responded to, and then another option listed above the selected question in the multi-select, the data from the option filled out gets moved to the newly selected option

**To Reproduce**
Steps to reproduce the behavior. If applicable please include the smallest possible XLSForm or XForm (as zip or link).

1. Upload form with repeating groups which contain a cascading multi select
2. Select an item that is close to the bottom of the multi-select list
3. Enter information
4. Select an item that is closer to the top of the multi-select list
5. View the information entered, it will be entered for the item higher on the list

This also is reproducible with the reverse, if two options are selected and the top option is removed, the data goes to the next option

**Expected behavior**
The information entered should have stayed with the correct select item

**Screenshots**

Option 5 has the data entered
![image](https://github.com/enketo/enketo-core/assets/74968475/927d83ba-e057-4cf4-a78b-3cf6676e041f)

Option 4 selected, data previously entered for 5 is now in 4
![image](https://github.com/enketo/enketo-core/assets/74968475/ad5dc01c-a698-49a6-bccf-0a62708bf0a9)

**Browser and OS (please complete the following information):**
Chrome Windows 11

**Additional details**
[aJHnrxBq4rauE8XaKsqjkk.xlsx](https://github.com/enketo/enketo-core/files/12907418/aJHnrxBq4rauE8XaKsqjkk.xlsx)

**Comment by lognaturel** [comment]
Bonjour @JacquelineMorrissette!

This looks to me like a fundamental issue with the form design. I believe a minimal reproduction would be a select multiple with a repeat that has values based on position in the select multiple. Is there an alternative behavior that you would expect given this form? If you also use ODK Collect, you may have noticed that it makes the flaw slightly harder to notice because it saves multiple selections in the order that they were selected. However, the same issue exists.

Here are some alternative form design options:
- "Unroll" the repeat: use a group for each possible option and use a relevance condition to show or hide each group based on whether the corresponding option is selected
- Use data collector hints and form structure to encourage the right behavior: put the select multiple on its own page and include a label that requests that data collectors don't move forward before being certain
- If you're using Collect for data collection, this is one of the reasons the "don't allow moving backwards in the form" option exists
- Use once() and/or trigger() to detect changes in the multi select and clear values in the repeats accordingly

If you still think there's an issue with Enketo not interpreting the form correctly, we can continue the conversation here. If you'd like to dig deeper into form design options, I recommend closing this issue and moving to [the forum](https://forum.getodk.org/) where we typically discuss form design.

**Comment by JacquelineMorrissette** [comment]
Thank you for the response @lognaturel, but I'm confused by it. Is this the expected behaviour then?

My expectation is that by selecting "Option 4" when"Option 5" is already selected and filled out would display the "Option 4" question as blank and the "Option 5" question to keep it's answer.

**Comment by lognaturel** [comment]
The form boils down to using the position in a repeat to look up a value in a select multiple response at the corresponding index, right? So if the indexes of values change in the select multiple, the corresponding value read from the select multiple in the repeat will be updated but the user-provided answers will stay in the repeat instance they are provided in. 

If that explanation doesn’t make sense, maybe you can point me to the form design mechanism you believe should make the kind of update you expect.

**Comment by JacquelineMorrissette** [comment]
Thank you for your help with troubleshooting. I will close this issue
