### ISSUE TITLE
'error' variable not defined

### ISSUE THREAD

**Issue by ivermac** [enketo/enketo-core#283]
The `error` variable [here](https://github.com/enketo/enketo-core/blob/714791182509f4f8351bc47a51b04765018d2704/src/js/Form.js#L233), [here](https://github.com/enketo/enketo-core/blob/714791182509f4f8351bc47a51b04765018d2704/src/js/Form.js#L245) and [here](https://github.com/enketo/enketo-core/blob/714791182509f4f8351bc47a51b04765018d2704/src/js/Form.js#L250) referenced by variable `y` as seen in the screen shot below is not defined. It seems to be defined in [here](https://github.com/enketo/enketo-core/blob/714791182509f4f8351bc47a51b04765018d2704/src/js/Form.js#L162) but may be it can't be accessed in `nodesToLoad` scope. `errMsg` is defined within the scope and used twice. Replacing `error` with `errMsg` seems to sort this out, what do you think? I will make a pull request with the change
![screen shot 2015-06-04 at 12 42 31 pm](https://cloud.githubusercontent.com/assets/1128227/7981327/ddbf9764-0ab6-11e5-8d8d-82b467444987.png)

**Comment by MartijnR** [comment]
Thanks Mark, 

It seems odd that this would be the cause of the ReferenceError (because it is defined and should be accessible). When testing it in uncompiled mode with a duplicate instanceID, I get the expected error message. 

However in compiled mode, something weird seems to be happening. The nodesToLoad.each() loop doesn't seem to be reached at all. I'm looking into that now.

**Comment by MartijnR** [comment]
Your fix indeed seems to have resolved this silent crash / referenceError, so thanks! The underlying cause is probably too much work to find out (something with r.js & uglify2) considering future plans. Another argument to switch to CommonJS modules and browserify!

**Comment by ivermac** [comment]
Glad to have helped!
