### ISSUE TITLE
No support for `big-image`

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#290]
There doesn't seem to be any support for the `big-image` media type:

> By default, itext “image” values are not clickable. However, if you also include a “big-image”, the image displayed by “image” will be clickable and will display a pannable, zoomable view of the file specified by “big-image”. The user interface must provide a way to go back to the form after opening a “big-image”. Specifying “big-image” alone has no effect, you must always include “image”.
> _https://opendatakit.github.io/odk-xform-spec/#supported-media-types_

If this is the case, then I guess it would require some extra in the XSL transform and then a widget to handle the big image action (or a default to just point to the URL).

**Comment by MartijnR** [comment]
Indeed, no support yet. Would be worthwhile to add (maybe as a css-only overlay). Indeed, if html markup is required, best to do in XSL sheet (and not in a widget). I'm not sure what Enketo currently does if image and big-image are provided.

**Comment by alxndrsn** [comment]
From my brief testing, it looks like currently `big-image` is just ignored, so it's not problematic.

Seems like reasonable behaviour when `big-image` is supplied would be for the XSL transform to convert to:
```html
<a href="$bigImageUri"><img src="$standardImageUri"></a>
```
Then if the `imageUri` values use the `jr:` protocols, it's up to the client how this gets handled.

**Comment by MartijnR** [comment]
Yes, this makes a lot of sense.

In CSS some kind of visual indication that the image is clickable perhaps. Blueish border maybe. Not sure.

To that end, and for the handler, it would probably be helpful to add a `big-image` class to the link (in the future more label links are planned to be added from xf:output elements to the question they refer to).

CSS-only display (without adding html) would be nice (if possible) because enketo-core doesn't have access to the modal dialogs that the app (e.g. enketo-express, enketo-legacy) uses .Similar to how the geowidget maps are revealed on touchscreen devices. Clicking the large image would hide it again.

**Comment by alxndrsn** [comment]
Had a go at creating a new widget, let me know what you think.

It doesn't currently include the images which are references in CSS.  The images are:
* prev
* next
* loading
* close

I'm not sure `prev` and `next` apply in this context.
For loading, does enketo already have a loading animation?
For close, what would be appropriate?  Is there something in enketo's glyph font?

**Comment by MartijnR** [comment]
Thanks! Will have a look (within a week I hope). I don't think enketo-core has a loading animation. Maybe enketo-core could just have a placeholder class for this, so that in a theme configuration (_variables.scss or _mixins.scss) it can be overridden with the app's default loader. 

Same with close button. We could add an .icon-close [here](https://github.com/enketo/enketo-core/blob/master/src/sass/core/_icons.scss) and then override this in the app that uses enketo-core. Or maybe do without a close button (clicking the image would close it).

I am also wondering whether prev and next apply. I don't think so.

**Comment by MartijnR** [comment]
Hi Alex, Just from looking at the lightbox widget code, this is much too heavy to include in enketo-core. I was thinking about implementing this very minimally with just a few lines of javascript and a css overlay. The feature has never been requested by a user and I just realized it is not actually supported in pyxform (so nobody uses it).

Thanks though! And isn't it great widgets can be overridden and added without touching enketo-core? :)

**Comment by MartijnR** [comment]
leaving this open as we still need to add this minimal widget some day

**Comment by alxndrsn** [comment]
No worries - good experience creating a new widget anyway :-)

**Comment by MartijnR** [comment]
now added to enketo-transformer v1.7.0
