### ISSUE TITLE
Native Date picker can’t reopen on Android device when dismissed by pressing the ‘Back' key

### ISSUE THREAD

**Issue by koros** [enketo/enketo-core#351]
Environment: Samsung tab 4 
Steps to reproduce:
Launch the date picker by selecting on a date input field, once the dialog shows dismiss it by either pressing the Back key or touching any other place on the screen.
Try to reopen the date picker by either selecting another date field or selecting the same field previously selected. 
Observation: The Date picker never gets relaunched unless the form activity is restarted.

You can use a sample apk file here: https://www.dropbox.com/s/dy94d5j9e1tyyzg/app-debug.apk?dl=0 to reproduce this issue. The first input is a date field. Thanks.

**Comment by MartijnR** [comment]
Thanks for this. Is it specific to a particular Android version, webview version? (I remember Samsung having messed up the native datepickers in the past).

@koros Can you reproduce it with this: http://s.codepen.io/MartijnR/debug/PZqeVY (probably not)
@alxndrsn Is this something you can reproduce in your app as well?

**Comment by koros** [comment]
@MartijnR Your suspicion is correct,it seems to manifest mainly on Samsung devices, i am using a Samsung Tab 4, i have tested on the Emulator and a nexus device and i am unable to reproduce it.

The new link you sent works perfectly on both the Emulator and a nexus device but still fails on the Samsung device(a bit weird also is the fact that on a Samsung it doesn’t launch the native date selector see the attached screenshot)

![device-2015-12-11-093857](https://cloud.githubusercontent.com/assets/1716093/11737574/8ae99786-9feb-11e5-8e68-31fa2a60ba40.png)

**Comment by koros** [comment]
If i use google chrome browser though, then it works i.e even on the Samsung device

**Comment by MartijnR** [comment]
Thanks Koros. Probably best to focus on the jsfiddle behaviour on the Samsung device (I presume you reproduced on the default browser, called "Internet"?).  Being able to reproduce it like that makes things a lot easier.

I don't have a Samsung device any more myself. I wonder if it's related to how "focus" and "blur" events are handled. Maybe add another text input to the JSFiddle and try to play around with changing focus.

I didn't find anything helpful online unfortunately.

**Comment by koros** [comment]
@MartijnR yeah i had used the default browser 'Internet' on the Samsung device, i wonder what is peculiar about it. Most probably the webview is using it as render engine within the app.

**Comment by alxndrsn** [comment]
@MartijnR @koros I can confirm seeing this bug on a couple of devices.  We have corresponding issues at https://github.com/medic/medic-webapp/issues/1691 and https://github.com/medic/medic-webapp/issues/1693.

IMO this is a bug in Chrome/Android Browser & `WebView` rather than a problem with Enketo.  I have seen the bug on Chrome version 30 on Android.  It seems like it's caused by the datepicker not being disposed correctly when the hardware-back-button (HBB) is pressed.  If you hide and re-show the `input` field that the datepicker is attached to (e.g. `jQuery('input[type=date]').hide().show()`) then the datepicker will function correctly again.

For a simple HTML page which will exhibit the bug: https://alxndrsn.github.io/medic-js-dbg/

-----

On android, we access enketo via a wrapper app, so on affected devices we replace the HTML5 datepicker with the android-Java [`DatePickerDialog`](https://developer.android.com/reference/android/app/DatePickerDialog.html).  To implement the same:

1. enketo plugin to replace `<input type="date">` with a replacement field: https://github.com/medic/medic-webapp/blob/8ad71b187f9bea62acd9bcd48a459bcdb128fc57/static/js/enketo/widgets/android-datepicker.js#L52
2. android wrapper methods to launch datepicker and return value to the WebView's DOM: https://github.com/medic/medic-android/blob/30182529f75ce6e37571cdd627cbb3d7c7000845/src/main/java/org/medicmobile/webapp/mobile/MedicAndroidJavascript.java#L91, https://github.com/medic/medic-android/blob/30182529f75ce6e37571cdd627cbb3d7c7000845/src/main/java/org/medicmobile/webapp/mobile/EmbeddedBrowserActivity.java#L84

**Comment by koros** [comment]
@alxndrsn thanks a lot i'll try the option you have suggested

**Comment by koros** [comment]
@alxndrsn Attached web view version
![device-2015-12-14-174022](https://cloud.githubusercontent.com/assets/1716093/11783921/b8ce0c26-a28a-11e5-89c1-ea66972085ef.png)

**Comment by MartijnR** [comment]
please reopen if necessary
