### ISSUE TITLE
Required constraints no longer validated on page change

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#360]
I am investigating further, but this seems to be a regression between `4.5.0` and `4.4.4`.

**Comment by alxndrsn** [comment]
Looking at the change at https://github.com/enketo/enketo-core/blob/master/src/js/Form.js#L559, either this line should read `required` instead of `data-required`, or I need to update my XSLTs.

**Comment by MartijnR** [comment]
Ah yes, makes sense. You need to update the XSL sheets because of [this change](https://github.com/enketo/enketo-xslt/commit/ea316872fa230037a68b98db158df88e25af06bf#diff-5effe98417fff7626de0c38427edbaacL809) that brings dynamic required expression support. It's actually not easy to warn users of enketo-core about this. 

Enketo Express always has a matching enketo-core and enketo-xslt function but that's a but cumbersome to check.

Should I just add the matching enketo-xslt version to the Readme?

**Comment by alxndrsn** [comment]
I think mentioning the XSLT change in the enketo-core changelog should be enough.  And many thanks for the link :-)

**Comment by MartijnR** [comment]
Ok, will do that from now onwards! Thanks.
