### ISSUE TITLE
Selected report does not update in UI after being edited

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#361]
In the _Reports_ tab, select a report, then edit its contents.  The contents do not update unless a hard-refresh is done.

This ticket was split from #1862

**Comment by alxndrsn** [comment]
Sorry, wrong repo!!!

**Comment by MartijnR** [comment]
that explains why I couldn't reproduce it ;)

On Tue, Feb 16, 2016 at 11:25 AM, Alex Anderson <notifications@github.com>
wrote:

> Sorry, wrong repo!!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enketo/enketo-core/issues/361#issuecomment-184812411>.
>

-- 
-- 
*Revolutionizing data collection since 2012.*

Enketo <https://enketo.org/>    |    LinkedIn 
<http://www.linkedin.com/company/enketo-llc>    |    GitHub 
<https://github.com/enketo>    |    Twitter <https://twitter.com/enketo>    
|    Blog <http://blog.enketo.org/>
