### ISSUE TITLE
grunt develop points to JS file that is not updated by grunt develop

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#393]
`forms/index.html` point to `build/enketo-bundle.min.js`.  This file does not seem to be updated by `grunt develop`, which is confusing.

Would it be reasonable to use the unminifed JS bundle in `forms/index.html`?

**Comment by MartijnR** [comment]
Yes, indeed. That's one of the things I always do (and sometimes forget and then get confused ;). The reason we cannot commit that change is that it would mess up enketo-core-performance-monitor (which is continuously running).

But not very helpful for enketo-core developers... Hmm. I wonder if we should cheat and change the name of the js file that `grunt develop` generates (since developers don't really have any use for the minified file).

**Comment by MartijnR** [comment]
or we can just let grunt build overwrite enketo-bundle.js with a minified version, in which case we could change index.html to point to enketo-bundle.js. That may be nicer.

**Comment by alxndrsn** [comment]
👍 to using non-minified in dev, as I guess minification would add a little delay to the update cycle.  I have slight reservations about having two artifacts with the same name though, as this might cause it's own confusions... but I guess we'll find out :¬)

**Comment by MartijnR** [comment]
Yes, we'll find out. I think there is no reason to have minification in enketo-core since it's meant to be bundled and minified with the apps's own JS files. So the only reason it remains is really because enketo-core-performance-monitor has been collecting data with a minified js file.
