### ISSUE TITLE
Filepicker: user-facing error messages are not translatable

### ISSUE THREAD

**Issue by alxndrsn** [enketo/enketo-core#466]
# Proposal:
## Change:
```js
Filepicker.prototype._showFeedback = function( message, status ) {
    message = message || '';
    status = status || '';
    // replace text and replace all existing classes with the new status class
    this.$feedback.text( message ).attr( 'class', 'file-feedback ' + status );
};
```
at https://github.com/enketo/enketo-core/blob/master/src/widget/file/filepicker.js#L187-L192

## To:

Something like:
```js
var t = require( 'translator' ).t;

Filepicker.prototype._showFeedback = function( status, message, args ) {
    message = message ? t(message, args) : '';
    status = status || '';
    // replace text and replace all existing classes with the new status class
    this.$feedback.text( message ).attr( 'class', 'file-feedback ' + status );
};
```

**Comment by alxndrsn** [comment]
Happy to submit a PR if this looks suitable :¬)

**Comment by MartijnR** [comment]
Thanks. User-facing error messages should be translatable indeed. 

I'm not sure if this is the best way though, because e.g. the file size error is displayed after an exception is caught with `catch(error)`. It might be easier to ensure `error.message` is translated before we throw it instead of passing a translation key and translation arguments.

So instead we could replace things like `new Error( 'File too large' );` with `t('error.filetoolarge', args)` and include an example string in the fake-translator for it. What do you think?

**Comment by alxndrsn** [comment]
I'm not really sure.  I generally feel that Error/Exception messages should be in English, and untranslated.  Otherwise there's always a danger that a bad translations could cause a confusing bug report.

Certainly in Java, I'd add relevant information to the Exception instance, and construct the user-facing text later from that (e.g. `FileTooLargeException`, with properties `maxAllowedFileSize` and `suppliedFileSize`).

I can see how it will keep things a bit simpler to have the Error message itself translated, though.

Let me know which you prefer, and I'll get a PR together.

**Comment by MartijnR** [comment]
Ok, I'm convinced. Let's do what you suggest. 

I see that in Enketo Express, I used this: https://github.com/kobotoolbox/enketo-express/blob/master/app/lib/custom-error.js. Maybe that's an okay way of doing it? However in this case we would maintain the message part as well. So `throw new TranslatedError('Bad', 'error.bad', args)`?
