### ISSUE TITLE
Discuss implementations and tests of area and distance functions common with JavaRosa (started as a suggestion to use GeographicLib)

### ISSUE THREAD

**Issue by dcbriccetti** [enketo/enketo-core#515]
In implementing distance calculations in JavaRosa (https://github.com/opendatakit/javarosa/pull/297),
we are considering using GeographicLib. It uses more accurate code for finding area and distance, and uses a different (more correct) Earth radius constant, as well as taking into account that the Earth is an oblate spheroid and not a sphere.

One problem with our using it is that users would get different results between JavaRosa and Enketo. Would this be a problem?

Would you like to use GeographicLib, too?

https://geographiclib.sourceforge.io/

**Comment by MartijnR** [comment]
Thanks Dave!

It depends on how much code it is. They seem they have done a great job with hiding the source code unfortunately. Will check it out later, with interest though. If it is too heavy, I'd prefer to leave our nice-and-tiny 'Equator' code and accept a small error away from the Equator. I always try to avoid big libraries for something like this.

In this particular case the issue with a difference between Enketo and Collect would be that the calculations change if a record collected with Collect is edited (after submission) in Enketo. The calculations would update. This is very common use case (in Ona, KoBoToolbox).

**Comment by dcbriccetti** [comment]
The source looks to be here:
https://sourceforge.net/p/geographiclib/code/ci/release/tree/
I found the link on the page I gave above.

Are you saying it would be a big deal if we had differences?

Have you also implemented “distance”? Perhaps JavaRosa needs to produce the same results as Enketo here, too. If you have, how do you calculate it?

I really dislike the idea of re-implementing a geo algorithm (they can be tricky as you probably know!), when there is a nice, well-tested library that will do it. And I’d very much like to remove our complicated hand-written area calculation code, too.

Thanks for giving this some thought.

**Comment by MartijnR** [comment]
Ah, I overlooked the fact that all languages are in the same repo. Thank you!

I haven't implemented `distance()` yet. 

I think you currently have a port of [this code](https://github.com/enketo/enketo-xpathjs/blob/master/src/engine.js#L5254) for area() (Enketo subcontracted SurveyCTO to add the code to JavaRosa way back, and we made sure to use the same algorithm/tests at that time). The code actually looks rather beautiful to me (in enketo-xpathjs).

That library looks rather large which makes me really reluctant to add it. Maybe the considerations are different for a web app, but I wonder if the loading performance cost is worth the benefit for the handful of users that would require that accuracy. What also plays a role for me is that if such accuracy is required, the use case is likely related to some advance **data analysis** and not to data collection. I am trying to be vigilant to not to turn Enketo into a bloated monster, because it would kill itself eventually. Are users complaining about area() in Collect?

> Are you saying it would be a big deal if we had differences?
Yes, I think so because it means that if a user edits a (Collect-collected) record with a geoshape and area calculation, and leaves the geoshape unchanged, it will be re-submitted with an unexpectedly updated area calculation.

**Comment by dcbriccetti** [comment]
Martijn, thanks for the background. It changes my mind. I now think we should leave the JavaRosa area code alone. Should we coordinate on the algorithm for distance?

**Comment by MartijnR** [comment]
Thanks Dave. Yes, definitely let's coordinate about `distance()` too and share tests. I was thinking about starting work on this next week (though nobody is pushing yet, so that may get delayed). I have the feeling the algorithm could be derived from the one used in `area()` and should be simpler but am not yet sure how exactly.

**Comment by dcbriccetti** [comment]
@MartijnR, what algorithm is this?
https://github.com/enketo/enketo-xpathjs/blob/master/src/engine.js#L5230
I looked for a reference to a paper or something.

**Comment by MartijnR** [comment]
@dcbriccetti, I think we got it from Leaflet who in turn go it from the OpenLayers https://github.com/Leaflet/Leaflet.draw/blob/3cba37065ea5be28f42efe9cc47836c9e3f5db8c/src/ext/GeometryUtil.js#L3-L20. Sorry, I'd normally put a reference in a comment but seem to have neglected to do this this time.

I'm noticing a 37m difference in Earth radius. This may have either been adjusted by them afterwards, or by us. I can try to find that discussion.

**Comment by dcbriccetti** [comment]
>I'm noticing a 37m difference in Earth radius.

I speculated that it was adjusted to make the results match those from the web site used to generate the test data. www.mapdevelopers.com/area_finder.php

**Comment by dcbriccetti** [comment]
Do you think this would meet our needs for distance between two points?

```
    private static double distanceBetween(LatLong p1, LatLong p2) {
        // Use the Spherical Law of Cosines, as described in various places, including https://www.movable-type.co.uk/scripts/latlong.html
        double Δλ = toRadians(p1.longitude - p2.longitude);
        double φ1 = toRadians(p1.latitude);
        double φ2 = toRadians(p2.latitude);
        return acos(sin(φ1) * sin(φ2) + cos(φ1) * cos(φ2) * cos(Δλ)) * MEAN_EARTH_RADIUS_METERS;
    }
```

**Comment by dcbriccetti** [comment]
Any chance we could improve the radius accuracy right away?

I got those nifty identifiers from the JavaScript implementation of the algorithm in the web page in my comment.

```
var φ1 = lat1.toRadians(), φ2 = lat2.toRadians(), Δλ = (lon2-lon1).toRadians(), R = 6371e3; // gives d in metres
var d = Math.acos( Math.sin(φ1)*Math.sin(φ2) + Math.cos(φ1)*Math.cos(φ2) * Math.cos(Δλ) ) * R;
```

**Comment by MartijnR** [comment]
This requires a change in our spec, so I've opened an issue here:

**Comment by dcbriccetti** [comment]
This algorithm, when given the funky Earth radius we’ve been using, produces polygon perimeters that match those produced by the web site www.mapdevelopers.com/area_finder.php that was used to produce the area test data in JavaRosa.

**Comment by MartijnR** [comment]
Thanks for doing all the work @dcbriccetti! I changed the distance code to make clear it's the same algorithm.
