### ISSUE TITLE
Count(/path/to/repeat/node) probably does not work when called from inside repeat

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-core#544]
_From @MartijnR on August 4, 2015 22:35_

due to position-injection related to [this deviation](http://opendatakit.github.io/odk-xform-spec/#a-big-deviation-with-xforms)

_Copied from original issue: kobotoolbox/enketo-express#283_

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on September 5, 2018 19:0_

Might be fixed. Check it.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on September 10, 2018 17:24_

https://docs.google.com/spreadsheets/d/1-EghHrvqAtrqY8dsWE4kapKlqIWFXHnSTTekEzxBq-g/edit#gid=0

[count-repeated.xml.txt](https://github.com/kobotoolbox/enketo-express/files/2367700/count-repeated.xml.txt)

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on September 10, 2018 17:25_

This is still an issue

**Comment by MartijnR** [comment]
I do not think it is feasible to fix this and it can easily be worked around by placing the count outside the repeat (and you could still use that value inside the repeat).

It will automatically be fixed once we stop doing the weird repeat thing (see spec link above). This is becoming realistic due to this great pyxform work: https://github.com/XLSForm/pyxform/pull/187
