### ISSUE TITLE
Grid Theme vertical spacing of list-nolabel is too large [1]

### ISSUE THREAD

**Issue by enketo-issue-mover** [enketo/enketo-core#560]
_From @MartijnR on May 9, 2015 21:41_

I vaguely remember there is a reason for this (maybe hints). To check if it can be resolved.

_Copied from original issue: kobotoolbox/enketo-express#204_

**Comment by MartijnR** [comment]
<img width="1212" alt="Screen Shot 2019-06-04 at 8 58 02 AM" src="https://user-images.githubusercontent.com/627350/58889918-e4090400-86a6-11e9-9828-eb707659f663.png">

**Comment by gushil** [comment]
@MartijnR could you please give the picture above an annotation about which one is not desirable and what expected result would be? Really appreciate it.

Thanks

**Comment by pbowen-oc** [comment]
@gushil - I discussed this with @MartijnR a few days ago. I think all 3 sections are meant to be made consistent with the spacing between other items. The first example section is using label appearance for the first item and list-nolabel appearance for the next two items. The next two sections are using table-list appearance on the group.

This screenshot was taken from the Widgets demo form - https://enke.to/::widgets

Scroll down to the Table section to see these. Note that you can download the XLS source for this form from a link near the top of the form.

**Comment by gushil** [comment]
@pbowen-oc sorry, I still not get it.

I think, the first table items vertical spacing is different with other tables because there is two lines of 'hint' or label for first label and there is just one line for the second table and no hint for last table.

If we remove the hint, vertical spacing is consistent.

![image](https://user-images.githubusercontent.com/60411/59548659-a5176000-8f7c-11e9-91ca-22e34991f1e3.png)

If we make the hints two lines, vertical spacing is consistent too.

![image](https://user-images.githubusercontent.com/60411/59548689-34247800-8f7d-11e9-9c77-89639ae35c0b.png)

**Comment by pbowen-oc** [comment]
@gushil - Can you compare this to a group of select_one items that have appearance = horizontal? This might have been logged about the appearance of list-nolabel items compared to standard horizontal items.

**Comment by gushil** [comment]
![image](https://user-images.githubusercontent.com/60411/59673903-507a1c00-91ec-11e9-95b0-cc4fb4765224.png)

The last table is select_one with appearance = horizontal

I think vertical spacing is consistent too.

**Comment by gushil** [comment]
[widgets_edited.xlsx](https://github.com/enketo/enketo-core/files/3301032/widgets_edited.xlsx)

Here is the form I use.

**Comment by MartijnR** [comment]
Thanks @gushil for finding out that it is consistent with select horizontal (columns-pack). In that case, best to leave as is and close this issue!
