### ISSUE TITLE
datetime question with midnight datetime default does not display time component

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#649]
![62851435-a5cc3880-bd18-11e9-99d8-f31d16ebc6c6](https://user-images.githubusercontent.com/627350/63056725-e0171080-bea5-11e9-934a-191fdb71942e.png)
![62851334-57b73500-bd18-11e9-9fb4-27c5683c10d5](https://user-images.githubusercontent.com/627350/63056748-eb6a3c00-bea5-11e9-9135-14f125aa3958.png)

**Comment by MartijnR** [comment]
After looking closer at this, the first of these does not appear to be a bug, or is a very different bug. I think the correct behavior would be to not recognize this value and show empty date and time (since the date format is not supported). Similarly, I think `"2016-10-08"` should be considered and invalid datetime.

**Comment by nanzhang01** [comment]
Regression happens for this issue. The current behaviour is like:
![image](https://user-images.githubusercontent.com/29697780/69065142-37ef8580-0a5a-11ea-83e2-b839182d7a4d.png).
This regression is introduced from https://github.com/enketo/enketo-core/commit/896e0b9a45c6e900811791447983b709bb07f306#diff-fb12358d88df2a187c353c9812b4014eR257,  `new Date('2019-11-01T00:00:00+08:00').toISOLocalString()` only returns the date part,  seems it's  by design result defined in enketo-xpathjs.
