### ISSUE TITLE
Relevant calculation causes the selected cascade choice to disappear for the first repeat after filling in information within a second repeat.

### ISSUE THREAD

**Issue by nanzhang01** [enketo/enketo-core#751]
**Describe the bug**
Relevant calculation causes the selected cascade choice to disappear for the first repeat after filling in information within a second repeat.

**To Reproduce**
1. Create survey with this xls form:  [test.xlsx](https://github.com/enketo/enketo-core/files/5621168/00_test_bugs.xlsx)
2. Select mon or tue;
3. Test1 quesiton appeared;
4. Select a dropdown value, i.e. "maybe";
5. Create a new repeat;
6. Select mon or tue in the second repeat, observe that "maybe" is cleared in test1 in the first repeat;

**Screenshots**
![00_bug_screenshot5](https://user-images.githubusercontent.com/29697780/100715666-7ac89500-33f2-11eb-850d-e9e8776cd2f1.gif)

**Comment by MartijnR** [comment]
Thanks. Looks like a serious bug!

**Comment by MartijnR** [comment]
http://localhost:8005/?xform=00_test_bugs.xml

**Comment by lognaturel** [comment]
Looks like expected behavior to me. The calculation is re-run and evaluates to '' because neither `none` nor `other` is selected. I think this is similar to https://github.com/enketo/enketo-core/issues/880#issuecomment-1101038570. If you'd like a dynamic default you can use something like https://docs.getodk.org/form-logic/#dynamic-defaults-from-form-data. Calculations may be re-evaluated at any time.
