### ISSUE TITLE
choice filter in repeat shows incorrect options for first repeat if multiple repeat instances are created

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#818]
**Describe the bug**
Itemsets (choice filter options) in the first repeat in a series of multiple repeat instances are not created correctly.

**To Reproduce**

1. Stick
[RCFT1.xml.txt](https://github.com/enketo/enketo-core/files/7239240/RCFT1.xml.txt)
  in test/temp, change extension to xml and open http://localhost:8005/?xform=RCFT1.xml
2. Create second repeat
3. Enter 3 in text input for second repeat
4. See how the choices in the first repeat changed.

**Expected behavior**
The itemset logic within a repeat should be isolated and not affect other repeat instances.

**Screenshots**

<img width="738" alt="Screen Shot 2021-09-27 at 4 27 57 PM" src="https://user-images.githubusercontent.com/627350/134982660-941db5f2-1fa2-401e-99b6-fa75de257a09.png">

**Browser and OS (please complete the following information):**
Enketo Core 6.0.0. It looks like this bug was introduced a long time ago **between versions 5.15.4 and 5.15.5**.

**Comment by MartijnR** [comment]
I will work on a fix.

**Comment by MartijnR** [comment]
culprit: https://github.com/enketo/enketo-core/commit/33800fcfc58b545152e7d373817d10dec5b3bcb8

**Comment by MartijnR** [comment]
* [x] add test for bug
* [x] add tests for new dom-utils functions

**Comment by eyelidlessness** [comment]
I'm reviewing #819. I can reproduce the issue with the steps you provided, but at first I did not think I could, due to an unrelated (to this bug) behavior. So I wanted to ask about this for clarification:

> Enter 3 in text input for second repeat

When I first did this, I did not see a radio button appear at all. Curious about the behavior (and issues with repeats generally), I clicked the repeat's + button to add another repeat. This is when I saw:

1. The radio was added in both existing repeats as described.
2. No new repeat was added.

Seeing this, my first thought was that adding the radios was performed on the `NewRepeat` (or `AddRepeat`) event, and that adding a repeat was suppressed by that somehow. But trying again, I now understand that:

1. The radio is not added until a native `change` event, which doesn't fire until the field loses focus.
2. Clicking (technically `mousedown`, and presumably also `pointerdown`) the + button (or anywhere) causes the field to lose focus, thereby triggering `change`, which is why the radios are added then.
3. The + button receives focus but, because the radios were added the + button is now further down the page and never receives a `mouseup`/`click`.

This is all generally surprising behavior to me, is it expected? Is there a reason we wouldn't want to use an `input` event (possibly debounced to prevent jank) to provide visual feedback _while typing_?

**Comment by MartijnR** [comment]
Thanks @eyelidlessness! The reason for choosing `change` is that updating a model value upon each keypress (e.g. in a long text field or when scrolling up and down through a number input field), would trigger the whole evaluation cascade of all the calculations, constraints, relevants etc that depend on that value which can be a performance issue. So if there are 20 dependent evaluations those would evaluated 10 times in quick succession if a text value is 10 characters.

One exception that comes to mind are the drawing/signature widgets. These are saved multiple times while drawing but are throttled. I don't quite remember the exact reason for this. Thankfully those questions are very unlikely to have dependent logic.

**Comment by eyelidlessness** [comment]
Thanks for the quick reply @MartijnR! That all makes sense conceptually. Is there an example form with particularly expensive calculations, or could you describe what cocktail of cascades I could use to produce one? It would be good to have for benchmarking/stress testing in general. But I'd also like to take a look at whether throttled `input` is feasible (or perhaps `MutationObserver`, which is particularly intended for performance-sensitive use cases). I think it could be a pretty big UX improvement.

**Comment by MartijnR** [comment]
We've got this: https://github.com/enketo/enketo-core-performance-monitor, but as you can see in the current graph it has challenges.... Unfortunately those forms are 1) not public, and I no longer even know who owns them, and 2) they don't measure performance during form traversal (only loading, validating, transforming).

The kind of form that would present a challenge is where an itemset querying a huge secondary instance is updated every time a value changes, and perhaps combined with a relevant condition that shows/hides a group, updates calculations, setvalues, constraints. One of the directly linked calculations could also have dependent calculations etc.

Yes, it's worth considering throttling an 'input' event perhaps, but I have a somewhat uneasy feeling about the consequences. It looks like XForms leave this up to us: https://www.w3.org/TR/xforms11/#evt-valueChanged. One issue could be timestamps with setvalue/xforms-value-changed if they are wrapped in `once()`, like `once(now())`, and in the future perhaps also the audit functionality. Actually, it would be good to check what ODK Collect does.

**Comment by lognaturel** [comment]
One of the big advantages of pages mode (the Collect default) is that page flip is a very natural place to commit values and trigger reevaluation. 

This decision point is relevant to field-lists in Collect. We made the decision to evaluate with every new character of input which is generally what users expect. In my experience, it’s not terribly common for large evaluation chains to be based on free text input. They’re typically based on selects. People do use free text to narrow down choices in a select (same as the search/autocomplete appearance). That can be slow to do character by character but the upside is that often the list is sufficiently filtered before typing the whole query. 

@MartijnR is absolutely right that recomputation at every character is not compatible with once(). I think we’ve always been able to find a better way to get the same result with a value-change action or something like that.
