### ISSUE TITLE
Update changelog of 6.0.1

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#856]
It is missing descriptions of the various fixes.

Similar update probably needed for enketo-express changelog as well.

**Comment by lognaturel** [comment]
Ideally there wouldn't be redundancy to manage. I'd love to move to Github releases and autogenerate release notes.

Is part of the reason that you've explicitly listed fixes up and down the dependency chain because of cases like https://github.com/enketo/enketo-core/issues/842 where changes in the deepest dependency aren't enough and also require changes in the parent tool?

**Comment by MartijnR** [comment]
The duplication of changes/fixes in the changelog was because I felt the benefits of being able to see when a transformer- or core-only fix was included in Enketo Express without having to dive into the dependencies. E.g. https://github.com/enketo/enketo-core/issues/853

(and vice-versa when an evaluator-only fix is included in enketo-core)

Autogenerating release notes would be great. I never managed to do this but mostly squashed each change/fix/feature into a single commit to make it easier to update the notes.

I was planning to create a PR for this though, but forgot. Will do! (after checking if it's already included in other PRs).
