### ISSUE TITLE
Binds on attributes work in Firefox but not other browsers

### ISSUE THREAD

**Issue by lognaturel** [enketo/enketo-core#917]
It's possible to bind to attributes:

```xml
<entities:entity dataset="trees" id=""/>
...
<bind nodeset="/data/meta/entities:entity/@id" jr:preload="uid" readonly="true()" type="string"/>
```

This works in Firefox but not in Chrome or Safari. 

## Reproduction
See [attribute-bind.xml.zip](https://github.com/enketo/enketo-core/files/9658961/attribute-bind.xml.zip)

For those with access to the Central QA server, it's hosted [here](https://test.getodk.cloud/#/projects/149/forms/attribute-bind/submissions). An easy way to view resulting XML for a submission is to navigate to that submission's feed (e.g. [here](https://test.getodk.cloud/#/projects/149/forms/attribute-bind/submissions/uuid%3Ad6792a9d-b16a-4720-a4d5-54e9c1e0ef29)) and change the # to v1 and add .xml ([e.g. [here](https://test.getodk.cloud/v1/projects/149/forms/attribute-bind/submissions/uuid%3Ad6792a9d-b16a-4720-a4d5-54e9c1e0ef29.xml)).

Sample submission made from Firefox:
```xml
<data id="attribute-bind" version="20220901">
    <q1 calc="10" bool="true" if="yes">5</q1>
    <calc>10</calc>
    <bool>true</bool>
    <if>yes</if>
...
</data>
```

Sample submission made from Chrome:
```xml
<data id="attribute-bind" version="20220901">
    <q1 calc="NaN" bool="false" if="no">5</q1>
    <calc>10</calc>
    <bool>true</bool>
    <if>yes</if>
...
```

The attributes get correct types and it looks as though values referenced from calculations are treated as blank.

**Comment by eyelidlessness** [comment]
I was about to give up hope of getting any insight into this today, but then found both the root cause and a potential solution at the same time. This is caused by passing the bound `Attribute` node as the `context` argument to the XPath evaluator. Apparently Firefox handles this just fine, but Chrome and Safari always return `null` nodes for any nodeset expression with an `Attribute` context.

Using the context's `ownerElement` produces the same behavior across browsers. I'm not sure whether that's a safe universal workaround, but sharing what I learned for discussion.

**Comment by lognaturel** [comment]
> caused by passing the bound Attribute node as the context argument to the XPath evaluator. 

Fascinating. My understanding from https://www.w3.org/TR/1999/REC-xpath-19991116/#section-Introduction is that the context node must be a node. I believe using the node that the attribute is on is correct. I will try to line up some definitive sources.

**Comment by lognaturel** [comment]
> My understanding

No, bad understanding! Right above what I quoted: "There are different types of nodes, including element nodes, attribute nodes and text nodes." So the context really should be the attribute node.

I've further confirmed this by changing the form linked above to use relative `calculate` expressions: 			
`<bind calculate="2 * .. " nodeset="/data/q1/@calc" type="string"/>`

This parents out of the attribute to the node itself. It works as expected in ODK Collect and Enketo from Firefox.

In looking into this I came across [this Chrome bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=179453&thanks=179453&ts=1362167145) which seems to still be open. This means only lowercase attribute names are supported in Chrome. We seem to be at the mercy of browsers for a lot of this.

**Comment by eyelidlessness** [comment]
To follow up on the above, there are two separate bugs here which present the same way.

1. When using binding to an attribute with a `calculate` or any other computation referencing an absolute nodeset XPath expression, that expression will fail to evaluate to the appropriate node(s) in Chrome and Safari, because using the attribute node as a context node fails. We believe that the appropriate immediate solution to this, in openrosa-xpath-evaluator, will be to evaluate absolute nodeset expressions with the context node's `ownerDocument` or `ownerDocument.documentElement`, because an absolute expression should implicitly have the same context.

2. When using a binding with a `calculate` or any other computation referencing `..` (or any sequence of `../..`), recomputation will never occur because `getRelatedNodes` and similar selector query-based relationship lookups will miss it. I've discussed that aspect of this bug with @lognaturel but to expand on it here, the same will potentially cause misidentification of same-named nodes at different places in the document structure (similar to some other bugs we've encountered around that). The specific relative expression without any node name is most likely to be used in `calculate` from attributes to parents, but could potentially be used in other computations as well.

   This falls into a growing category of bugs and unknowns about how Enketo identifies data dependencies, which has resurfaced fairly frequently around various computations, repeat/group hierarchies, and so on. I was hoping that during/after a break that I'd be able to come up with a revelatory quick fix recommendation for this case, but I haven't thought of one which wouldn't be high risk. That this particular area of the current design continues to show up in so many seemingly unrelated cases continues to motivate me to prioritize both a more holistic look at how Enketo builds the computation dependency graph, and to consider targeted ways we might be able to move certain high risk areas of the codebase towards pragmatic nearer-term solutions.

Regarding @lognaturel's remark about being at the mercy of browsers, I'll add here the same comment I made in chat earlier: there are available, open source extensible XPath implementations without any dependency on native XPath. We may want to seriously consider exploring those, both to limit our dependence on browser implementations which have little if any interest in X*Anything* and to reduce the surface of custom XPath functionality we maintain to the parts which are actually specific to Enketo and related projects.

**Comment by lognaturel** [comment]
> bugs and unknowns about how Enketo identifies data dependencies

https://github.com/enketo/enketo-core/issues/823

> available, open source extensible XPath implementations without any dependency on native XPath

Enketo used to use https://github.com/enketo/enketo-xpathjs which is a fork of XPathJS. The problem is that it was really slow. It was replaced in late 2019: https://github.com/enketo/enketo-core/pull/688 It's scary to think that we don't really know what funky evaluators end user might be using. But it still seems like our best bet to me.

**Comment by lognaturel** [comment]
This was sufficiently addressed by https://github.com/enketo/openrosa-xpath-evaluator/pull/166
