### ISSUE TITLE
Invalid geo selector

### ISSUE THREAD

**Issue by lognaturel** [enketo/enketo-core#953]
Just got a report of a `SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '.question input[data-type-xml="geopoint"] ...` about https://github.com/enketo/enketo-core/blob/master/src/widget/geo/geopicker.js#L80 The selector was simplified following https://github.com/enketo/enketo-core/issues/920

There is no geo question in the form.

This user users the [CryptoTab Browser](https://cryptobrowser.site/en/) on Android. From the user's perspective, they are using the latest version of their browser. @yanokwa says he's received other reports of that error since #920.

Is there further simplification of that query possible? Or can it short circuit if the form has no `geopoint`, `geotrace`, `geoshape`? If neither of those is possible, we should show a browser incompatibility message in that case.

**Comment by eyelidlessness** [comment]
This is fascinating in so many ways! I opened the CryptoTab link to see if I could find out more about its rendering engine, and... thought I'd stumbled on a spam site. Anyway, from another site I've learned that it uses Chromium (no surprise there), but I haven't found any information about how up to date it is. That said, this selector failing corresponds to support for [`:not` in Selectors Level 4](https://caniuse.com/css-not-sel-list), and it appears to have been supported in Chromium (and all other major browsers) since January 2021. So if an up to date CryptoTab install is running a Chromium build from before that, that's **highly worrying** for their users (but I don't know what I'd expect besides worry, from a browser specifically devoted to mining crypto).

Anyway, while I'd normally be inclined to close this because January 2021 is well beyond our browser support window, I think there's something appealing about addressing this besides browser support!

As I've noted several times, CSS selector queries are by far our biggest performance concern in Core. This particular selector has frequently showed up as a performance hog in profiling. And  the question about short-circuiting for forms without geo widgets got me thinking: I think we mat be able to go further than that, and short circuit **all widgets** which don't apply to a given form. This could be a worthwhile performance win and address this particular issue at the same time.
