### ISSUE TITLE
Widgets-disabled class probably not correct

### ISSUE THREAD

**Issue by MartijnR** [enketo/enketo-core#986]
https://github.com/enketo/enketo-core/blob/166af8c0d9bfe37ad65c4dbc5a805b458bae0948/src/js/widgets-controller.js#L101C35-L101C35

Just happened to see this and wanted to report it, but have not investigated further. Looks like this should be `'widgets-disabled'` (and if this causes an issue, tests are not be covering it yet)

**Comment by eyelidlessness** [comment]
Good catch! While investigating this, I discovered a few things:

- While there is a typo in the class removed on the linked line, the same typo is present [where the class is added](https://github.com/enketo/enketo-core/blob/166af8c0d9bfe37ad65c4dbc5a805b458bae0948/src/js/widgets-controller.js#L126).
- That would be a relief, except the correct spelling is used in [both](https://github.com/enketo/enketo-core/blob/166af8c0d9bfe37ad65c4dbc5a805b458bae0948/src/js/widgets-controller.js#L97-L99) [checks](https://github.com/enketo/enketo-core/blob/166af8c0d9bfe37ad65c4dbc5a805b458bae0948/src/js/widgets-controller.js#L122-L124) for the presence of the class on self/ancestors. This is one of two bugs I found: the `enable` method is never applied.
- Worse, there is a related bug, where detecting which widgets implement `enable` and/or `disable` incorrectly fails most if not all of the time, because it's checking [whether the form uses relevance expressions](https://github.com/enketo/enketo-core/blob/166af8c0d9bfe37ad65c4dbc5a805b458bae0948/src/js/widget.js#L19), but the check occurs [before that information is available](https://github.com/enketo/enketo-core/blob/166af8c0d9bfe37ad65c4dbc5a805b458bae0948/src/js/form.js#L306-L308).

**All of this** is trivially fixed. Unfortunately, as @MartijnR noted, there is a lack of test coverage... tests which really should have caught these cases. It will probably also be pretty straightforward to introduce pertinent test coverage, to fix and keep these optimizations as intended. *However*, the last thing I found:

- I was surprised that neither of these bugs were caught by existing tests. While investigating I also peppered some logging in targeted places, looking for tests/fixtures which might have appropriate setup to exercise these cases. When I went to isolate such a test, the logging I expected to see disappeared. This is how I found the second bug, but it also revealed worrying test isolation failures. For this reason, I'm hesitant to trust the straightforward tests and trivial fixes I have in mind until I'm able to identify and address the test isolation issue(s?).

As such, the plan for now (as discussed with @lognaturel wrapping up my day yesterday) is to temporarily roll back the changes which introduced the bugs discussed above. This will allow more time to investigate further, and reintroduce these optimizations with more reliable test coverage.
